### PR TITLE
[fix] topologically sort aliases

### LINKED ISSUE #140: [bug] Generated aliases are sorted alphabetically, not topologically
## What happened?
Generated aliases in python are sorted alphabetically, which might fail to compile if aliases reference each other in a topological manner

## What did you want to happen?
Might need to implement a topological sort of aliases

### PR DESCRIPTION
**Pull request by ferozco**
Closes #140

## Before this PR
We would generate invalid code when handling nested aliases. This was especially problematic since we did not have previously have type information when we were ordering snippets.

## After this PR
==COMMIT_MSG==
Topologically sort all aliases
==COMMIT_MSG==

## Possible downsides?
The amount of complexity and how much of a hack it is. I think the correct solution is to drop support for python2 and then generate each class in its own file and let python deal with it

### CODE REVIEW

**Review by iamdanfox — APPROVED** [review]

File: conjure-python-core/src/main/java/com/palantir/conjure/python/poet/PythonFile.java [hunk 1]
```diff
@@ -55,7 +56,16 @@ default void emit(PythonPoetWriter poetWriter) {
...
+            contents().stream()
+                    .filter(snippet -> !(snippet instanceof AliasSnippet))
+                    .sorted((ps1, ps2) -> Comparator.comparing(PythonSnippet::idForSorting).compare(ps1, ps2))
+                    .forEach(poetWriter::emit);
+
+            List<AliasSnippet> sortedSnippets = PythonAliasTopologicalSorter.getSortedSnippets(contents().stream()
+                    .filter(snippet -> snippet instanceof AliasSnippet)
+                    .map(snippet -> (AliasSnippet) snippet)
+                    .collect(Collectors.toList()));
+            sortedSnippets.forEach(poetWriter::emit);
```
Comment (iamdanfox) [inline conjure-python-core/src/main/java/com/palantir/conjure/python/poet/PythonFile.java:68]: Why is it important to do all the aliases last if we're really carefully tracking dependencies between snippets?

Comment (ferozco) [reply conjure-python-core/src/main/java/com/palantir/conjure/python/poet/PythonFile.java:68]: We are only topologically sorting the aliases themselves. Everything else is assumed to be defined earlier. We don't need to worry about references to aliases from beans, since they occur within the scope of the class which is evaluated after the global scope of the whole file

Comment (iamdanfox) [reply conjure-python-core/src/main/java/com/palantir/conjure/python/poet/PythonFile.java:68]: Ah right of course because python is interpreted, if we declare a class Foo and it uses Bar in the body, it doesn't matter if Bar hasn't been defined yet because by the time anyone can actually _use_ Foo, it will have been!
